"""add_event_days_table

Revision ID: 0f9f11bbb377
Revises: 4d5e6f7a8b9c
Create Date: 2026-07-03 12:30:45.125083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f9f11bbb377'
down_revision: Union[str, Sequence[str], None] = '4d5e6f7a8b9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_days',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('day_of_week', sa.String(length=10), nullable=False),
    sa.Column('weather', sa.String(length=20), nullable=True),
    sa.Column('headliner_artist', sa.String(length=255), nullable=True),
    sa.Column('expected_attendance', sa.Integer(), nullable=True),
    sa.Column('peak_hour_start', sa.Integer(), nullable=True),
    sa.Column('peak_hour_end', sa.Integer(), nullable=True),
    sa.Column('opening_time', sa.Integer(), nullable=True),
    sa.Column('closing_time', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_days')
    # ### end Alembic commands ###
